name: Read Sample File

on:
  push:
    branches: ["main"]

jobs:
   show-file:
       runs-on: windows-latest

       steps:
           - name: checkout repository
             uses: actions/checkout@v3

           - name: Display sample.txt content
             run: |
               echo "----------Content of sample.txt----------"
               cat sample.txt
               echo "-----------------------------------------"
