name: Read Sample File

on:
  workflow_dispatch

jobs:
   show-file:
       runs-on: self- hosted

       steps:
           - name: checkout repository
             uses: actions/checkout@v3

           - name: Display sample.txt content
             run: |
               echo "----------Content of sample.txt----------"
               cat sample.txt
               echo "-----------------------------------------"
